### ISSUE TITLE
No window menu

### ISSUE THREAD

**Issue by T00rk** [flathub/io.github.spacingbat3.webcord#59] opened 2023-08-08 10:33 UTC
I'm using v 4.3.0 and there is no button on the top right of the window.

![Capture d’écran du 2023-08-08 12-29-36](https://github.com/flathub/io.github.spacingbat3.webcord/assets/593708/9f53ce0c-39e0-4c38-b659-296af19e9805)

**Comment by axtloss** [comment] 2023-08-08 11:03
duplicate of #58

**Closed by axtloss** 2023-08-08 11:03 UTC
